document.write('<br><br><br><br><br>');
document.write('<div class=" blog">');
document.write('    <ul>');
document.write('        <li><a href="/">⬅️Back to HOME🏠</a></li>');
document.write('    </ul>');
document.write('</div>');
document.write('<HR style="border:1 dashed #987cb9" width="50%" color=#987cb9 SIZE=1>');
document.write('<table class="table_footer">');
document.write('    <tbody>');
document.write('        <td>');
document.write('            Originally written in Markdown(.md). Convert Markdown to HTML via <a');
document.write('                href="https://showdownjs.com/">Showdown</a><br>');
document.write('            © Copyright 2022-2023 PeterHU. Hosted by <a href="https://pages.github.com/">GitHub Pages</a> and <a href="https://reactjs.org">React App</a>.<br/>');
document.write('            Last updated:');
document.write('            <script>');
document.write('                document.write(document.lastModified);');
document.write('            </script>');
document.write('            </div>');
document.write('        </td>');
document.write('    </tbody>');
document.write('</table>');
